# Generated by Django 3.0.5 on 2021-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsweb', '0002_cartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=400)),
                ('phone', models.EmailField(max_length=254)),
                ('email', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('datetime', models.CharField(max_length=200)),
            ],
        ),
    ]
