# Generated by Django 3.0.5 on 2021-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsweb', '0003_trackorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo1', models.CharField(max_length=200)),
                ('demo2', models.CharField(max_length=200)),
            ],
        ),
    ]
